version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx/
  #   restart: on-failure
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "443:443"
  #   networks:
  #     - inception_network
  #     - outside_network
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: on-failure
    expose:
      - "3306"
    ports:
     - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - inception_network
    environment:
      - DB_USER_PASS=${DB_USER_PASS}
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: on-failure
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      inception_network:
        ipv4_address: 172.22.0.3
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_CHARSET=${DB_CHARSET}
      - WP_SITEURL=${WP_SITEURL}
      - WP_HOME=${WP_HOME}
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}

networks:
  inception_network:
    ipam:
      config:
        - subnet: "172.22.0.0/24"
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/stan/Projects/42/inception/volumes/wordpress'
  mysql_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/stan/Projects/42/inception/volumes/mysql'
