version: '3'

services:
  nginx:
    container_name: nginx
    build: ./srcs/nginx/
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
  mariadb:
    container_name: mariadb
    build: srcs/mariadb
    expose:
      - "3306"
    ports:
     - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    # networks:
    #   - inception_network
  wordpress:
    container_name: wordpress
    build: srcs/wordpress
    ports:
      - "9000:9000"
    expose:
      - "9000"
    # networks:
    #   - inception_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html

# networks:
#   inception_network:
#     name: inception_network

volumes:
  wordpress_volume:
    external: true
  mysql_volume:
    external: true